<div class="row detect-about">
    <div class="col-xs-12 row-margin">
        <h1 id="content-heading">About Us</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <p class="about-pgraph">
            Langa Cheshire Home was established by volunteers in 1990 as the third Cheshire Home in the Western Cape. When we 
            first started there were only 3 residents and today we have 26, all of whom are profoundly disabled.
        </p>
        <p class="about-pgraph">
            The initial capital funding was given to us by the Department of the Premier and our operating expenses were
            provided by the national Cheshire Homes organisation. 
        </p>
    </div>
    <div class="col-md-4">
        <img id="about1-img" class="about-img" src="<?php echo $this->basePath('img/about1.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/about1.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/about1@2x.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/about1@3x.jpg 3x') ?>" 
                               alt="Home lounge area"/>
    </div>
    <div id="map-container" class="col-md-4">
        <div id="map">
            <h2>Map</h2>
            <p class="about-pgraph">
                Rhodes Avenue<br> 
                Langa<br> 
                Cape Town<br> 
                7455
            </p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13239.166209698715!2d18.5287249!3d-33.946489!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ae6fdef8dd1c457!2sCheshire+Home+Langa!5e0!3m2!1sen!2sza!4v1471560572325" 
                    height="300" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div id="line-break-padding" class="row"><div id="line-break" class="col-md-8"></div></div>
<div class="row">
    <div id="about2-img-section" class="col-md-4">
        <img class="about-img" src="<?php echo $this->basePath('img/about2.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/about2.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/about2@2x.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/about2@3x.jpg 3x') ?>" 
                               alt="Home tv"/>
    </div>
    <div class="col-md-4">
        <p class="about-pgraph">
            The Department of Social Development issues a salary grant for our staff and a disability grant for our residents.
            The disability grant totals R1500 per resident, 75% of which goes to the home for board and lodging. 
        </p>
        <p class="about-pgraph">
            It is our hope that we will be able to accommodate many more residents, but we need your help so please, 
            <a class="pgraph-link" href="<?php echo $this->url('donate') ?>">donate now.</a>
        </p>
    </div>
</div>