<div class="row detect-gallery">
    <div class="col-xs-12 row-margin">
        <h1 id="content-heading">Gallery</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-2">
        <img id="gallery-img1" class="gallery-top-img" src="<?php echo $this->basePath('img/gallery_security.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_security.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_security.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_security@3x.jpg 3x') ?>" 
                               alt="Front security gate"/>
        <p class="about-pgraph gallery-pgraph">
            Keeping our residents safe is very important to us. Apart from security gates and burglar bars, we also have a big
            driveway gate that remains closed at all times.
        </p>
    </div>
    <div class="col-md-2">
        <img id="gallery-img2" class="gallery-img gallery-top-img" src="<?php echo $this->basePath('img/gallery_space_inside.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_space_inside.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_space_inside.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_space_inside@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            We have a large indoor space where our residents can socialise with each other.
        </p>
    </div>
    <div class="col-md-2">
        <img id="gallery-img3" class="gallery-img gallery-top-img" src="<?php echo $this->basePath('img/gallery_space_outside.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_space_outside.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_space_outside.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_space_outside@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            Currently our lawn makes up much of our outdoor area, but we hope our expansion plans will be funded to make 
            better use of this space.
        </p>
    </div>
    <div class="col-md-2">
        <button id="gallery-close-btn">X</button>
        <img id="gallery-img4" class="gallery-img gallery-top-img" src="<?php echo $this->basePath('img/gallery_flowers.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_flowers.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_flowers.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_flowers@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            Assorted plants and flowers can be seen around the grounds adding to the warmth of our home atmosphere.
        </p>
    </div>
    <div id="mission-map-container" class="col-md-4">
        <div id="map">
            <h2>Map</h2>
            <p class="about-pgraph">
                Rhodes Avenue<br> 
                Langa<br> 
                Cape Town<br> 
                7455
            </p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13239.166209698715!2d18.5287249!3d-33.946489!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ae6fdef8dd1c457!2sCheshire+Home+Langa!5e0!3m2!1sen!2sza!4v1471560572325" 
                    height="300" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-2 gallery-middle-img">
        <button id="gallery-prev-btn">V</button>
        <img id="gallery-img5" class="gallery-img" src="<?php echo $this->basePath('img/gallery_garden.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_garden.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_garden.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_garden@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            An offering from our sustained garden project which we use to cut on catering costs.
        </p>
    </div>
    <div class="col-md-2 gallery-middle-img">
        <img id="gallery-img6" class="gallery-img" src="<?php echo $this->basePath('img/gallery_empty.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_empty.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_empty.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_empty@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            With some support through donations and volunteers we could bring in more residents and brighten up the home 
            with a fresh coat of paint to help lift their spirits.
        </p>
    </div>
    <div class="col-md-2 gallery-middle-img">
        <img id="gallery-img7" class="gallery-img" src="<?php echo $this->basePath('img/gallery_stretch_wheelchair.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_stretch_wheelchair.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_stretch_wheelchair.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_stretch_wheelchair@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            Specially modified wheelchairs are provided for residents who have more severe physical disabilities.
        </p>
    </div>
    <div class="col-md-2 gallery-middle-img">
        <button id="gallery-next-btn">V</button>
        <img id="gallery-img8" class="gallery-img" src="<?php echo $this->basePath('img/gallery_laugh.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_laugh.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_laugh.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_laugh@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            One of the greatest gifts we can give our residents is an environment where they are surrounded by people who 
            share the same difficulties as they do as well as dedicated caregivers.
        </p>
    </div>
</div>
<div class="row" id="gallery-footer-margin">
    <div class="col-md-2">
        <img id="gallery-img9" class="gallery-img last-row" src="<?php echo $this->basePath('img/gallery_hobbie.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_hobbie.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_hobbie.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_hobbie@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            We do our best to provide materials to keep our residents engaged and to encourage stimulation.
        </p>
    </div>
    <div class="col-md-2">
        <img id="gallery-img10" class="gallery-img last-row" src="<?php echo $this->basePath('img/gallery_rdp.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_rdp.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_rdp.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_rdp@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            Help us to bring back these types of programmes that can be used to build independence and self-reliance in 
            our residents.
        </p>
    </div>
    <div class="col-md-2">
        <img id="gallery-img11" class="gallery-img last-row" src="<?php echo $this->basePath('img/gallery_donate_food.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_donate_food.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_donate_food.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_donate_food@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            A souvenir from a food donation programme. We're so grateful for the kindness shown to our home and we hope to 
            forge more relationships with companies who will sponsor similar events.
        </p>
    </div>
    <div class="col-md-2">
        <img id="gallery-img12" class="gallery-img last-row" src="<?php echo $this->basePath('img/gallery_sun.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/gallery_sun.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/gallery_sun.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/gallery_sun@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
        <p class="about-pgraph gallery-pgraph">
            Some of our residents even need electric wheelchairs to get around, but they are still able to get outside and 
            enjoy the warm sunshine.
        </p>
    </div>
</div>