<div class="row detect-history">
    <div class="col-xs-12 row-margin">
        <h1 id="content-heading">History</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <p class="about-pgraph">
            The organisation has been named after Leonard Cheshire, who was a bomber pilot in World War II. After his war 
            experiences he felt a strong need to validate his life and was drawn to the idea of service to others.
        </p> 
        <p class="about-pgraph">
            In 1948 Leonard heard of a fellow service man who had fallen terminally ill, this man was in dire straits with no 
            family, means and without a place to go.
        </p>
        <p class="about-pgraph">
            Leonard took Arthur in and cared for him until his death. From such a small and unplanned beginning was the world 
            wide Cheshire organisation to grow. Today there are Cheshire organisations and homes all over the world.
        </p>
    </div>
    <div id="mission-map-container" class="col-md-4">
        <div id="map">
            <h2>Map</h2>
            <p class="about-pgraph">
                Rhodes Avenue<br> 
                Langa<br> 
                Cape Town<br> 
                7455
            </p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13239.166209698715!2d18.5287249!3d-33.946489!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ae6fdef8dd1c457!2sCheshire+Home+Langa!5e0!3m2!1sen!2sza!4v1471560572325" 
                    height="300" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div id="line-break-padding" class="row"><div id="line-break" class="col-md-8"></div></div>
<div class="row" id="history-footer-margin">
    <div class="col-md-8">
        <p class="about-pgraph">
            Cheshire Homes started in South Africa in 1965 and the first Home, Queensburgh, was opened in 1968. 
            Today, there are six Branches and eighteen Homes in this country, providing residential accommodation to 
            profoundly and permanently disabled adults and children.      
        </p>
        <p class="about-pgraph">
            In addition, many outreach programmes provide services such as day care, respite care, community based care, and 
            crèche type care. These outreach programmes operate from established Cheshire Homes.  
        </p>
        <p class="about-pgraph">
            There are also a number of independent living units attached to Cheshire Homes, where those residents who are 
            sufficiently confident can live as independently as possible, secure in the knowledge that expert care is within call.
        </p>
        <p class="about-pgraph">
            Cheshire Homes continues to grow, and we hope in the future to offer a wider range of services in response to the 
            expanding needs of persons with disabilities. 
        </p>
    </div>
</div>