<div class="row detect-needs">
    <div class="col-xs-12 row-margin">
        <h1 id="content-heading">Needs</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <p class="about-pgraph">
            Our home has the same needs that your home does such as food and cleaning materials. We need to pay our electricity
            bill, do the laundry, and provide security. Our residents also require specially adapted bathrooms, a range of 
            assistive devices to ensure independence and full time staff to care for them. In order for us to continue to give 
            support and care to people with disabilities we need all the help we can get so please, help us to help them by
            making a <a class="pgraph-link" href="<?php echo $this->url('donate') ?>">donation</a> today.
        </p> 
        <p class="about-pgraph">
            Donating money or clothing is not the only way you can help our home. We welcome any and all volunteers who help us 
            to achieve our goals by giving of their time and expertise in various ways. We especially need volunteers to help 
            out at the home itself and any assistance regarding outreach programmes would mean the world to our residents.
        </p>
    </div>
    <div id="mission-map-container" class="col-md-4">
        <div id="map">
            <h2>Map</h2>
            <p class="about-pgraph">
                Rhodes Avenue<br> 
                Langa<br> 
                Cape Town<br> 
                7455
            </p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13239.166209698715!2d18.5287249!3d-33.946489!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ae6fdef8dd1c457!2sCheshire+Home+Langa!5e0!3m2!1sen!2sza!4v1471560572325" 
                    height="300" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div id="line-break-padding" class="row"><div id="line-break" class="col-md-8"></div></div>
<div class="row">
    <div class="col-md-4" id="about2-img-section">
        <img class="about-img" src="<?php echo $this->basePath('img/needs.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/needs.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/needs@2x.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/needs@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
    </div>
    <div class="col-md-4">
        <p class="about-pgraph">
            As you can see we have plenty of open space. When we first opened we had planned on expanding over time
            to accommodate more residents and even provide Early Childhood Development for children with disabilities. 
            We are calling out to all fundraisers and corporate entities who generously sponsor organisations such as ours to 
            please help make this dream a reality. Please <a class="pgraph-link" href="<?php echo $this->url('contact') ?>">
            contact us</a> if you think you can help us in any way.
        </p>
    </div>
</div>