<div class="row detect-newsletter">
    <div class="col-xs-12 row-margin">
        <h1 id="content-heading">Newsletter</h1>
    </div>
</div>
<div class="row" id="newsletter-header-pad">
    <div class="col-md-4 newsletter-header" id="newsletter-left-link">
        <a class="newsletter-link-white" href="https://www.facebook.com/Langa-Cheshire-Home-297799850587464/?skip_nax_wizard=true" target="_blank">Tell a friend</a>
    </div>
    <div class="col-md-4 newsletter-header" id="newsletter-right-link">
        <a class="newsletter-link-white" id="newsletter-link-float" href="http://localhost:8383/Newsletter/index.html" target="_blank">Open in your own browser</a>
    </div>
    <div id="mission-map-container" class="col-md-4 newsletter-map-align">
        <div id="map">
            <h2>Map</h2>
            <p class="about-pgraph">
                Rhodes Avenue<br> 
                Langa<br> 
                Cape Town<br> 
                7455
            </p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13239.166209698715!2d18.5287249!3d-33.946489!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ae6fdef8dd1c457!2sCheshire+Home+Langa!5e0!3m2!1sen!2sza!4v1471560572325" 
                    height="300" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div class="row" id="mission-footer-margin">
    <div class="col-md-8">
        <div class="newsletter-crimson-line"></div>
        <img id="newsletter-logo" class="newsletter-img" src="<?php echo $this->basePath('img/lch_logo.png') ?>" alt="Langa Cheshire Home logo"/>
        <div class="newsletter-crimson-line"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <img class="newsletter-img" src="<?php echo $this->basePath('img/banner.jpg') ?>" alt="Langa Cheshire Home entrance"/>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <div class="newsletter-grey-block">
            <h1 class="newsletter-heading">LANGA CHESHIRE HOME</h1>
            <p class="newsletter-pgraph">
                Langa Cheshire Home provides stable,caring and nurturing residential care to people 
                with severe physical disabilities. People from disadvantaged communities 
                who would otherwise be unable to receive the care and support they so 
                desperately need.	
            </p>
        </div>
    </div>
</div>
<div class="row newsletter-grey-pad">
    <div class="col-md-4 newsletter-grey-background">
        <div class="newsletter-white-block-left">
            <h2 class="newsletter-section-heading">MISSION</h2>
            <p class="newsletter-pgraph">
                Our mission is to assist people with disabilities 
                throughout the world, regardless of their 
                colour, race or creed, by providing the 
                conditions necessary for their physical, 
                mental and spiritual well-being.
            </p>
        </div>
    </div>
    <div class="col-md-4  newsletter-grey-background">
        <div class="newsletter-white-block-right">
            <h2 class="newsletter-section-heading">VISION</h2>
            <p class="newsletter-pgraph">
                We believe that each person, whatever his or 
                her disability, is a uniquely valuable individual 
                and that people with disabilities should have 
                the personal freedom to pursue their 
                aspirations and take their own place in the 
                world..
            </p>
        </div>
    </div>
</div>
<div class="row newsletter-grey-pad">
    <div class="col-md-4 newsletter-grey-background">
        <div class="newsletter-img-block">
            <img class="newsletter-img" src="<?php echo $this->basePath('img/charity_shop.jpg') ?>" 
                                        srcset="<?php echo $this->basePath('img/charity_shop.jpg 1x') ?>, 
                                                <?php echo $this->basePath('img/charity_shop@2x.jpg 2x') ?>,
                                                <?php echo $this->basePath('img/charity_shop@3x.jpg 3x') ?>" 
                                        alt="Charity shop"/>
        </div>
    </div>
    <div class="col-md-4 newsletter-grey-background">
        <div class="newsletter-white-block-right">
            <h2 class="newsletter-section-heading">GOALS</h2>
            <p class="newsletter-pgraph">Unquestioning recognition of their full human rights.</p>
            <p class="newsletter-pgraph">Standards of excellence in all aspects of care from both staff and volunteers.</p>
            <p class="newsletter-pgraph">The opportunity to take an effective part at every level in running our services.</p>  
        </div>
    </div>
</div>
<div class="row newsletter-grey-pad">
    <div class="col-md-4 newsletter-grey-background">
        <div class="newsletter-white-block-left">
            <h2 class="newsletter-section-heading">SERVICES</h2>
            <p class="newsletter-pgraph">
                It is very important to us to make sure our
                residents are properly cared for. We provide 
                many services to make their lives easier.
            </p>  
            <a href="<?php echo $this->url('services') ?>">
                <button class="newsletter-btn">View Service</button>
            </a>
        </div>
    </div>
    <div class="col-md-4 newsletter-grey-background">
        <div class="newsletter-img-block newsletter-img-float">
            <img class="newsletter-img" src="<?php echo $this->basePath('img/garden.jpg') ?>" 
                                        srcset="<?php echo $this->basePath('img/garden.jpg 1x') ?>, 
                                                <?php echo $this->basePath('img/garden@2x.jpg 2x') ?>,
                                                <?php echo $this->basePath('img/garden@3x.jpg 3x') ?>" 
                                        alt="Garden"/>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <div class="newsletter-grey-block" id="newsletter-contribute-block">
            <div class="newsletter-contribute-line"></div>
            <h1 class="newsletter-heading">CONTRIBUTE</h1>
            <div class="newsletter-contribute-line"></div>
            <p class="newsletter-pgraph" id="newsletter-contribute-margin">
                Langa Cheshire Home relies heavily on donations. Please visit our donation page today to make
                a contribution and help improve the lives of all our residents.	
            </p>
            <a href="<?php echo $this->url('donate') ?>">
                <button class="newsletter-btn">Donate</button>
            </a>
        </div>
    </div>
</div>
<div class="row newsletter-grey-pad">
    <div class="col-md-8" id="newsletter-footer">
        <div class="col-md-8">
            <p class="newsletter-pgraph" id="newsletter-unsubscribe">
                You can unsubscribe 
                <a id="newsletter-footer-link" href="<?php echo $this->url('unsubscribe') ?>">here</a> 
                and we won’t make you feel guilty. 
            </p>
        </div>
        <div class="col-md-4">
            <a href="<?php echo $this->url('contact') ?>">
                <svg class="envelope" viewBox="10 0 70 72" width="40px" height="30px">
                    <polygon class="envelope-part" fill="#fff" points="28.3,23.9 2.4,4 2.4,51.5 "/>
                    <polygon class="envelope-part" fill="#fff" points="59,25.5 44.7,36.6 29.9,25.2 3.7,53.1 85.6,53.1 "/>
                    <polygon class="envelope-part" fill="#fff" points="60.6,24.3 86.8,4 86.8,51.5 "/>
                    <polygon class="envelope-part" fill="#fff" points="44.6,34 85.2,2.7 4,2.7 "/>
                </svg>
            </a>
            <a href="https://www.facebook.com/Langa-Cheshire-Home-297799850587464/?skip_nax_wizard=true" target="_blank">
                <svg class="social-icon" viewBox="0 0 70 70" width="30px" height="30px">
                    <defs><style>.cls-1{fill:#fff;}</style></defs> 
                    <g id="Layer_2" data-name="Layer 2">
                        <g id="facebook">
                            <path class="cls-1" d="M52,0H12A12,12,0,0,0,0,12V52A12,12,0,0,0,12,64H52A12,12,0,0,0,64,
                                  52V12A12,12,0,0,0,52,0ZM42.08,32H35.75V56.37H26.33V32.12H20.58V23.87h5.75S24.5,7.62,34.58,
                                  7.62h8.75v8h-4.5s-3.08,0-3.08,2.67v5.17h7.66Z"/>
                        </g>
                    </g>
                </svg>
            </a>
            <a href="https://twitter.com/LangaCheshire" target="_blank">
                <svg class="social-icon" viewBox="0 0 70 72" width="30px" height="30px">
                    <g id="Layer_2" data-name="Layer 2">
                        <g id="twitter">
                            <g id="bird">
                                <path class="cls-1" d="M55,0H12A12,12,0,0,0,0,12V54.38a12,12,0,0,0,12,12H55a12,12,0,0,0,12-12V12A12,
                                      12,0,0,0,55,0Zm-.37,22.06C53.63,51.44,25.75,61.56,7,49.69c0,0,9.13,1,15.38-4.5,0,0-6.87,
                                      0-10-7.62,0,0,3.88.75,4.88-.25a11.12,11.12,0,0,1-8.5-10.75,7.38,7.38,0,0,0,4.63,
                                      1.13s-8-5.87-2.87-14.5c0,0,8.63,11.13,22.38,11.38-1.75-10.5,9.63-18.12,18.75-9.75a26,
                                      26,0,0,0,6.75-2.75,11.18,11.18,0,0,1-4.5,6.25,27.08,27.08,0,0,0,5.75-1.87A13.92,13.92,0,0,1,
                                      54.63,22.06Z"/>
                            </g>
                        </g>
                    </g>
                </svg>
            </a>
        </div>
    </div>
</div>