<div class="row detect-services">
    <div class="col-xs-12 row-margin">
        <h1 id="content-heading">Services</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-8">
        <p class="about-pgraph">
            We provide many services essential to our residents care, but we would love to be able to add services that help to 
            improve their quality of life as well. In the past we have integrated outreach programmes that provided our residents 
            with some much needed stimulation such as an art day. In recent times we have been unable to provide similar 
            activities, but with your help we can bring those programmes back and encourage our residents to be more independent
            and self reliant so that they can take control of their own lives.
        </p> 
        <p class="about-pgraph">
            The services we currently offer include:
        </p>
        <p class="about-pgraph">
            - Full time residential care<br>
            - Community based care<br>
            - Daily meals<br>
            - Wheelchair hire or sales<br>
            - Independent living
        </p>
    </div>
    <div id="mission-map-container" class="col-md-4">
        <div id="map">
            <h2>Map</h2>
            <p class="about-pgraph">
                Rhodes Avenue<br> 
                Langa<br> 
                Cape Town<br> 
                7455
            </p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13239.166209698715!2d18.5287249!3d-33.946489!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ae6fdef8dd1c457!2sCheshire+Home+Langa!5e0!3m2!1sen!2sza!4v1471560572325" 
                    height="300" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div id="line-break-padding" class="row"><div id="line-break" class="col-md-8"></div></div>
<div class="row">
    <div class="col-md-8">
        <h2 id='goals-heading'>Code of Ethics</h2>
        <p class="about-pgraph">
            In every area of interaction is Cheshire Homes, staff, service users and volunteers, at all times to:
        </p> 
        <p class="about-pgraph">
            - Adhere to the highest standard of honesty<br>
            - Respect the dignity and human rights of others<br>
            - Protect the confidentiality of information<br>
            - Respect the Cheshire Charter<br>
            - Consider the best interests of society<br>
            - Be consistent and fair in all dealings<br>
            - Accept full responsibility for their conduct<br>
            - Promote Cheshire service in a true and accurate manner
        </p>
    </div>
</div>