<div class="row detect-vision">
    <div class="col-xs-12 row-margin">
        <h1 id="content-heading">Vision</h1>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <p class="about-pgraph">
            Our vision is for persons with disabilities to be able to live with dignity and without discrimination 
            in the community and within Cheshire Homes.
        </p> 
        <p class="about-pgraph">
            We have long since opening had a 4 phase plan which entails expanding to make room for another 74 residents 
            bringing the total to 100. We implore any individual or company who is able to help to please 
            <a class="pgraph-link" href="<?php echo $this->url('contact') ?>">contact us.</a> You will make a huge difference to so many lives.
        </p>
    </div>
    <div class="col-md-4">
        <img class="about-img" src="<?php echo $this->basePath('img/vision.jpg') ?>" 
                               srcset="<?php echo $this->basePath('img/vision.jpg 1x') ?>, 
                                       <?php echo $this->basePath('img/vision@2x.jpg 2x') ?>,
                                       <?php echo $this->basePath('img/vision@3x.jpg 3x') ?>" 
                               alt="Residents getting some sun"/>
    </div>
    <div id="map-container" class="col-md-4">
        <div id="map">
            <h2>Map</h2>
            <p class="about-pgraph">
                Rhodes Avenue<br> 
                Langa<br> 
                Cape Town<br> 
                7455
            </p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d13239.166209698715!2d18.5287249!3d-33.946489!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x5ae6fdef8dd1c457!2sCheshire+Home+Langa!5e0!3m2!1sen!2sza!4v1471560572325" 
                    height="300" frameborder="0" allowfullscreen></iframe>
        </div>
    </div>
</div>
<div id="line-break-padding" class="row"><div id="line-break" class="col-md-8"></div></div>
<div class="row" id="mission-footer-margin">
    <div class="col-md-8">
        <h2 id='goals-heading'>Goals:</h2>
        <p class="about-pgraph">
            - To alleviate discrimination against people with disabilities<br>
            - To provide early childhood development<br>
            - To support livelihood development<br>
            - To create independent living opportunities<br>
            - To promote service user participation in  service development<br>
        </p>
    </div>
</div>